import './globals.css';
import NavList from '../components/NavList';
import Script from 'next/script';
// import Providers from '@/components/Providers';
// import { config } from "@fortawesome/fontawesome-svg-core";

// config.autoAddCss = false;

export const metadata = {
  title: 'Films App 2',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* <Providers> */}
          <main>
            <nav>
              <NavList />
            </nav>
            {children}
          </main>
        {/* </Providers> */}
        {/* <Script src='https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js' /> */}
      </body>
    </html>
  )
}
